'use strict';
const { Router } = require('express');
const c = require('../controllers/goalController');
const r = Router();
r.get('/',                    c.listGoals);
r.get('/:id',                 c.getGoal);
r.post('/',                   c.createGoal);
r.patch('/:id',               c.updateGoal);
r.delete('/:id',              c.deleteGoal);
r.get('/:id/milestones',         c.getMilestones);
r.post('/:id/milestones',        c.addMilestone);
r.patch('/:id/milestones/:mid',  c.updateMilestone);
r.delete('/:id/milestones/:mid', c.deleteMilestone);
r.get('/:id/tasks',              c.getGoalTasks);
r.post('/:id/tasks',             c.linkTask);
r.delete('/:id/tasks/:taskId',   c.unlinkTask);
r.post('/:id/recalc',            c.recalcProgress);
module.exports = r;
